### ISSUE TITLE
How to set the username and password?

### ISSUE THREAD

**Issue by chenx2018** [blairanderson/netlify-plugin-password-protection#5]
Thanks for your awesome plugin!

May I know how to set the username and password? Also, is it possible to only protected some files in a particular folder? After being authorized, is it possible to NOT SHOW login again?

Thanks!

**Comment by blairanderson** [comment]
https://github.com/blairanderson/netlify-plugin-password-protection/blob/master/index.js

Please read through the code. 

This plugin takes your static html files and encrypts them with a single password. theres no database of users/passwords/etc.

**Comment by blairanderson** [comment]
> possible to NOT SHOW login again?

on successful password, store in cookies/localstorage. 
then check cookies/localstorage for the password

**Comment by chenx2018** [comment]
Thanks a lot!

**Comment by something0000** [comment]
> Thanks a lot!

hey did u implement it
